### ISSUE TITLE
optional enums don't work in abilities (card creator)

### ISSUE THREAD

**Issue by patrickwieth** [DecentralCardGame/frontend#103]
reproduce:
add ability
pick any, 
pick as effect draw place [ TAG ]
it is possible not to select a tag, because this is an optional parameter! But if no tag is selected the ability is not properly added to the card and thus ends up having no ability.

This bug will also happen with all other enums on all other optional parameters

This should actually be handled at L261 in AbilityComponent.vue but seemingly it's not

**Comment by lxgr-linux** [comment]
Is this still a thing?

**Comment by patrickwieth** [comment]
yes

**Comment by patrickwieth** [comment]
but not anymore
