### ISSUE TITLE
When editing a card and changing the card artwork the ability is removed even if the button is not pressed

### ISSUE THREAD

**Issue by patrickwieth** [DecentralCardGame/frontend#107]
![image](https://user-images.githubusercontent.com/10943178/169707243-248b14d7-6102-445e-ac57-bb2d924ae863.png)

when I upload a new image over a card, then the abilities are removed even if the button is not pressed here (clear all abilities)

in this past this worked, but it may have stopped working now after we separate the card artwork and the card content in the handling of card editing?

**Comment by lxgr-linux** [comment]
I can't reproduce in development.

**Comment by patrickwieth** [comment]
I have fixed this already, sorry for not closing this issue :D
