### ISSUE TITLE
use authz for harmless tx

### ISSUE THREAD

**Issue by patrickwieth** [DecentralCardGame/frontend#109]
some transactions are done often, so using a ledger or similar device everytime would be super annoying

therefore we want to do these txs with different wallet address which has the rights to do this for the real account via authz

txs are:
vote on cards, play/sign game, edit/save card, create user

**Comment by patrickwieth** [comment]
this is partially implemented, it works, but is not nice for the user

**Comment by lxgr-linux** [comment]
This is solved due to #205
