### ISSUE TITLE
card title cut off

### ISSUE THREAD

**Issue by patrickwieth** [DecentralCardGame/frontend#144]
sometimes card title text is cut off

**Comment by patrickwieth** [comment]
I thought I fixed this with 6ca51bc295e458678bee7477341218998acf095b 
but the bug is sometimes still visible, very rarely and only on the left side of the card title, so we are getting closer :D

**Comment by lxgr-linux** [comment]
On which views does this occur?

**Comment by patrickwieth** [comment]
everywhere but its rare, easiest is to vote on 100 cards, you will see it

**Comment by lxgr-linux** [comment]
Are we just talking card title or also card content?

**Comment by patrickwieth** [comment]
it can also happen on the card rulestext, but this is fixed as well, maybe now it still happens but only on every 1000th card, we'll see

**Comment by lxgr-linux** [comment]
It does happen quite often, see review

**Comment by patrickwieth** [comment]
please try again with the shameless fix

**Comment by patrickwieth** [comment]
<img width="333" alt="image" src="https://user-images.githubusercontent.com/10943178/213193482-b8d8b8b2-d567-4d6f-b0b6-78eeb7cce7c1.png">
fuq

**Comment by lxgr-linux** [comment]
big fuq
