### ISSUE TITLE
Rebuild voting page

### ISSUE THREAD

**Issue by lxgr-linux** [DecentralCardGame/frontend#156]
*"As a player I want a good looking an functional voting page"*

This involves:
 - Restructuring of voting page like defined in [figma](https://www.figma.com/file/xbMDLqz6rSN0qJjiafxe8a/UX-Crowd-Control-Website-2.0?node-id=286%3A283)
 - ~~logic update to just show voting page when the user is logged in @patrickwieth?~~
 - Nice icon to show, when all cards are voted on, instead of the "you can't vote nomore" text @AnnyBuh

**Comment by patrickwieth** [comment]
We had this in the past, that voting disappeared in the menu until user was logged in. It sucked. Noah and Jannik assumed voting is no longer working and even though they have to login from time to time to edit their cards, still they did not notice that voting is there (once they logged in).
It is much better to communicate to the players they can vote. And if they decide they want to vote they get on a page where it says "yes voting is possible, but please login"
Furthermore voting page also leads to voting results, which are always accessible, also when logged out.

**Comment by patrickwieth** [comment]
"Restructuring of voting page loke defined in figma"
if it already exists, please link figma here (@AnnyBuh)

**Comment by AnnyBuh** [comment]
https://www.figma.com/file/xbMDLqz6rSN0qJjiafxe8a/UX-Crowd-Control-Website-2.0?node-id=1017%3A148&t=ECPXv6u6SzShoTNS-1

**Comment by lxgr-linux** [comment]
This ticket is just for the voting Page and not council.

**Comment by AnnyBuh** [comment]
figma doesn't have links to individual pages. the voting page is also in that link

**Comment by AnnyBuh** [comment]
![Voting no new cards](https://user-images.githubusercontent.com/48418575/209468219-2ce6ae00-9284-4cfc-afed-1ff20b8efe07.jpg)
![Voting no new cards](https://user-images.githubusercontent.com/48418575/209468221-ae9de095-c3fa-41d3-acd3-29611920c070.png)

**Comment by patrickwieth** [comment]
yes council is a sub-page of the voting page

**Comment by lxgr-linux** [comment]
@AnnyBuh That's now how it looks like

![image](https://user-images.githubusercontent.com/64218491/210137407-028ec359-6343-416b-881f-479c4cc83d5c.png)

**Comment by lxgr-linux** [comment]
@AnnyBuh That's now how it looks like

![image](https://user-images.githubusercontent.com/64218491/210137407-028ec359-6343-416b-881f-479c4cc83d5c.png)

**Comment by AnnyBuh** [comment]
resolved in call
