### ISSUE TITLE
Cardcreator cardname character limit

### ISSUE THREAD

**Issue by lxgr-linux** [DecentralCardGame/frontend#158]
*"As a user I want the cardcreator to limit the cardname length, before sending a transaction to the chain and getting an error about name length"*

This may be achieved by adding a hard limit to cardname input field, and, when it's hit, show a warning text, that the cardname can be max 25 chars.

**Comment by patrickwieth** [comment]
there are 2 ways to do it:
a) classic, use maxLength on <input> -> the user will hit a limit and not be able to input more characters
b) javascript interacty -> the user will get a notification and is warned that his actions are inacceptable! (more work to implement)
@AnnyBuh

**Comment by AnnyBuh** [comment]
a) seems more straight forward
