### ISSUE TITLE
open Edit Card in new tab

### ISSUE THREAD

**Issue by AnnyBuh** [DecentralCardGame/frontend#186]
How much work is it to make open Edit Card open in new tab just like advanced card info? I'm updating the card artworks and there is huge pain and time consumption in always having to go back to gallery and click next until I reach the end of the cards again. If I open the card in advanced card info, I am logged out of the wallet for some reason.

**Comment by patrickwieth** [comment]
You can go to edit from the advanced card view already. So to solve your pain, you can just open the advanced card view for all cards you want to edit and then click edit from there.

That the Card Creator is also a link like the advanced card view (if you want to edit) is not hard to do. Currently you navigate to it, but it can also become a link as well, the big problem will remain, that you have to login again then. The whole behavior of the wallet will change anyway in the near future, so let's check this again then

**Comment by AnnyBuh** [comment]
If I open the card in advanced card info, I am logged out of the wallet for some reason.

**Comment by patrickwieth** [comment]
it is very likely it will take longer than just next week
