### ISSUE TITLE
Minor spelling mistakes on the HP (https://crowdcontrol.network/#/)

### ISSUE THREAD

**Issue by LordLordose** [DecentralCardGame/frontend#187]
There are minor spelling mistakes on the HP (https://crowdcontrol.network/#/)

**Comment by LordLordose** [comment]
Myself not being an English native speaker, I still think one would use 'that' (and without a comma) instead of which. Additionally, I am rather sure there is a noun missing where I marked it.

![555](https://user-images.githubusercontent.com/125970893/220315769-b2f0f289-ebeb-487a-8bad-1eaa56265fd4.jpg)

**Comment by LordLordose** [comment]
So here are my suggestions for spelling on the HP. It is British English now, which can, of course, be easily changed, if the decision is to use American English.
Please note that I only checked spelling. I did not make any stilistic suggestions, or think about the contents.
[Uploading Rechtschreibung CC HP.docx…]()

**Comment by patrickwieth** [comment]
https://github.com/DecentralCardGame/frontend/pull/192
