### ISSUE TITLE
Profile pic loading spinner confuses new users

### ISSUE THREAD

**Issue by patrickwieth** [DecentralCardGame/frontend#201]
new users that just registered see a forever spinning loading symbol for their profile pic, which confuses them (they wait until it stops, but it never stops). 

![image](https://github.com/DecentralCardGame/frontend/assets/10943178/e1b7fe66-0920-4c0a-a48f-2fae4563fc33)

We should change this and if retrieving a pic was not possible, just display a ? or a X or something that communicates more clearly that no image is available.

**Comment by patrickwieth** [comment]
![image](https://github.com/DecentralCardGame/frontend/assets/10943178/278871d3-e0a8-4980-be08-f1a2c1cc86a7)

furthermore for new users it is totally unclear that there might be a button to change the profile pic (once you have a card)

**Comment by lxgr-linux** [comment]
I know this happens, bu i couldn't reproduce

**Comment by patrickwieth** [comment]
to reproduce you only need to create a new user
