### ISSUE TITLE
Line where the bg repeats

### ISSUE THREAD

**Issue by AnnyBuh** [DecentralCardGame/frontend#24]
<img width="1536" alt="Bildschirmfoto 2021-02-21 um 21 19 43" src="https://user-images.githubusercontent.com/48418575/108636147-1d416300-748c-11eb-8a56-7b3c0e9802ad.png">

There is a white line, when the BG repeats. It only appears when i don't have the browser in fullscreen.

**Comment by patrickwieth** [comment]
please try again

**Comment by annadezhu** [comment]
it's still there for me

**Comment by patrickwieth** [comment]
with the last update of background.svg I fixed all these white lines, if another one comes up, please open a new issue (I'm afraid, this can always happen, when the amount of content changes)
