### ISSUE TITLE
Remove RulesText from card model

### ISSUE THREAD

**Issue by patrickwieth** [DecentralCardGame/frontend#262]
The idea here is to completely auto-generate RulesText from the cardobject. This must only happen after Marius has build the feature in the gameclient as well, because currently the gameclient uses the RulesText generated in the frontend.

**Comment by lxgr-linux** [comment]
What is the state of this?

**Comment by patrickwieth** [comment]
depends on these
https://github.com/DecentralCardGame/cardobject/issues/98

https://github.com/DecentralCardGame/gameclient/issues/254

might be possible to move on here? @nlsui

**Comment by patrickwieth** [comment]
This should be doable now
