### ISSUE TITLE
About page issues.

### ISSUE THREAD

**Issue by Niko-Sn** [DecentralCardGame/frontend#302]
https://crowdcontrol.network/#/about/team
- link to white paper links to NotFound
- roadmap looks like shit

**Comment by lxgr-linux** [comment]
> link to white paper links to NotFound

This is knowm

> roadmap looks like shit

This is true. Do you want to rebuild it @patrickwieth ?

**Comment by patrickwieth** [comment]
I can do it, not now as chain upgrade has higher priority, but after that. Furthermore the link to whitepaper works for me, maybe one needs to be logged in to github and/or have access to our Organization?

**Comment by lxgr-linux** [comment]
@patrickwieth You missed the point, he meant the actual [whitepaper page](https://crowdcontrol.network/#/about/whitepaper) in the about section, not the link in the footer, which does not work, since it has not been implemented yet.

**Comment by lxgr-linux** [comment]
I think an embed of the whitepaper pdf, it's added in figma, but i didn't have time do that yet. And like you said, other things have prio rn.
