### ISSUE TITLE
Gallery cards too small

### ISSUE THREAD

**Issue by Niko-Sn** [DecentralCardGame/frontend#311]
![image](https://github.com/user-attachments/assets/719cfc3b-1b73-4aaf-9a76-6815c41b5797)
Cant read any of the text on cards. on my laptop monitor

**Comment by patrickwieth** [comment]
Yes I think together with #306 the gallery should have better grid logic

**Comment by patrickwieth** [comment]
@Niko-Sn please report back if it is now ok (the cards are a lot bigger now)

**Comment by Niko-Sn** [comment]
This is 95% better, thanks!

**Comment by patrickwieth** [comment]
95% is 2 sigma mean derivation, which comes from exp(-1/2 (x-mu)²) fidibus here is a lollipop: 🍭
