### ISSUE TITLE
Indication that more cards will be loaded in gallery?

### ISSUE THREAD

**Issue by Niko-Sn** [DecentralCardGame/frontend#312]
Would it be possible to get this info from blockchain to display to the user via a loading wheel at the bottom or something? When searching for cards - sometimes its rly confusing, not knowing if more cards will be loaded or if what Im seeing is everything.

**Comment by patrickwieth** [comment]
Absolutely possible. First you do a request to blockchain node, which returns all card ids that match your search criteria and then all cards are asnyc fetched.
I can certainly build the functionality and then if a designer has a design we can pull in the design for that (I will just do some numbers on the bottom?)

**Comment by patrickwieth** [comment]
became obsolete with changes from #327
