### ISSUE TITLE
some Abilities overlap in the gallery

### ISSUE THREAD

**Issue by QriouZz** [DecentralCardGame/frontend#40]
![image](https://user-images.githubusercontent.com/73444376/121680277-a3c09580-cab9-11eb-9380-f82e07cda90f.png)

**Comment by QriouZz** [comment]
![Uploading image.png…]()

**Comment by QriouZz** [comment]
![image](https://user-images.githubusercontent.com/73444376/121680997-89d38280-caba-11eb-8615-2de18b11f900.png)

**Comment by patrickwieth** [comment]
bug fixed with ecf31c363316d746bab5e378a7de35208c7d8035
