### ISSUE TITLE
Save card on Safari 

### ISSUE THREAD

**Issue by patrickwieth** [DecentralCardGame/frontend#45]
Saving card as png (download) does drop the image on Safari Browser BUG

**Comment by patrickwieth** [comment]
@AnnyBuh is this still an issue?

**Comment by AnnyBuh** [comment]
Yes. It's still saving as a blank without the picture. 
![undefined](https://user-images.githubusercontent.com/48418575/121918526-cadbc900-cd3e-11eb-9fcc-0408b481549f.png)

**Comment by patrickwieth** [comment]
this might be related or even the same source of trouble as #35
